import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'contribute',
  description: 'Add a new advisor to the meclis agora via PR.',
};

export default function ContributePage() {
  return (
    <article className="space-y-10">
      <header className="space-y-3">
        <p className="smallcaps text-bronze text-[11px]">contribute</p>
        <h1 className="font-display text-3xl text-parchment">add an advisor</h1>
        <p className="font-serif text-parchment/85 text-base leading-relaxed max-w-2xl">
          one folder, one PR. the agora is canonical: every merged advisor appears on this site
          within a deploy and becomes installable through the cli.
        </p>
      </header>

      <section className="parchment p-6 sm:p-8 space-y-5">
        <h2 className="smallcaps text-bronze-deep text-[11px]">the shape</h2>
        <pre className="font-mono text-[12px] leading-6 bg-ink-deep text-parchment p-4 overflow-x-auto">{`collection/
└── <slug>/
    ├── advisor.md          # H1 must equal displayName
    ├── advisor.json        # validated against _schema/advisor.schema.json
    ├── sprite.png          # 896×1200 transparent PNG
    ├── sprite.thumb.png    # generated by \`bun run generate-thumbs\`
    └── references.md       # optional bibliography`}</pre>

        <h2 className="smallcaps text-bronze-deep text-[11px]">the steps</h2>
        <ol className="space-y-2 text-ink/90 text-[15px] leading-relaxed list-decimal pl-6">
          <li>
            pick a public thinker. <strong>enough</strong> public material to build a tight pack of
            their voice — essays, books, podcasts, interviews. living people who would loathe the
            project on principle deserve restraint.
          </li>
          <li>
            pick a kebab-case slug. the folder name and <code>advisor.json.slug</code> must match.
          </li>
          <li>
            write <code>advisor.md</code> with sections in order: identity, philosophy, voice rules,
            frameworks, quotes, ethical line. ~8-12k words.
          </li>
          <li>
            write <code>advisor.json</code> matching{' '}
            <a
              href="https://github.com/woosal1337/meclis/blob/main/collection/_schema/advisor.schema.json"
              target="_blank"
              rel="noopener noreferrer"
            >
              the schema
            </a>
            .
          </li>
          <li>
            add <code>sprite.png</code> at 896×1200 with a transparent background. the prompt the
            existing sprites use lives at{' '}
            <a
              href="https://github.com/woosal1337/meclis/blob/main/scripts/generate-sprites.md"
              target="_blank"
              rel="noopener noreferrer"
            >
              scripts/generate-sprites.md
            </a>
            .
          </li>
          <li>
            run <code>bun run generate-thumbs</code> to produce <code>sprite.thumb.png</code>.
          </li>
          <li>
            optional: <code>references.md</code> listing the source material distilled.
          </li>
          <li>
            open the PR. ci validates schema, sprite dimensions, slug match, and section presence.
          </li>
        </ol>

        <h2 className="smallcaps text-bronze-deep text-[11px]">the ethical line</h2>
        <p className="text-ink/90">
          every pack is a model of someone&apos;s public voice. use only publicly available material.
          do not fabricate quotes. the synthesis line at the end of every advisor block makes the
          imitation explicit. if a living thinker asks for their pack to be removed, open an issue
          and we will pull it.
        </p>

        <h2 className="smallcaps text-bronze-deep text-[11px]">authoring guide</h2>
        <p className="text-ink/90">
          the long-form guide lives in{' '}
          <a
            href="https://github.com/woosal1337/meclis/blob/main/docs/authoring-advisors.md"
            target="_blank"
            rel="noopener noreferrer"
          >
            docs/authoring-advisors.md
          </a>
          . read it once, then look at the three seed packs in{' '}
          <a
            href="https://github.com/woosal1337/meclis/tree/main/collection"
            target="_blank"
            rel="noopener noreferrer"
          >
            collection/
          </a>{' '}
          for tone and length.
        </p>
      </section>
    </article>
  );
}
